### ISSUE TITLE
Increment the version.

### ISSUE THREAD

**Issue by MarkusTieger** [rbi/rddns#3]
https://github.com/rbi/rddns/pull/2 got merged. To keep it organized, you should increment the version.
Also a new docker image hasn't been published and the version in the Cargo.toml should be synchronized with the latest tag.

**Comment by rbi** [comment]
I planed to release a version 1.0.0 next so that's why I wrote this number in the `Cargo.toml`. As I haven't got so much time for testing I'd rather go with a version 0.4.0 next. Coincidentally it seams that the version number can no be left out of the `Cargo.toml` now all together. That makes it possible to decide on a version number at the end of a development cycle now instead of the beginning.

I've updated the [dev tag](https://hub.docker.com/layers/sirabien/rddns/dev/images/sha256-bb14d8ae477b823132ea360d19811cf2bd97435eb845ef8f31f75e9db710006d?context=repo) of the Docker image . Could you test if it work as expected? If it works I'll create a v0.4.0 Docker tag.

There isn't any build automation at the moment btw. The workflow definition in the `.github` folder are from a time when the workflow feature was still in beta. It seams that there where incompatible changes in the mean time.

**Comment by MarkusTieger** [comment]
It worked for me without any problem or bug.

**Comment by rbi** [comment]
Thanks for testing. I've tagged the Docker Image as v0.4.0 and also created a Git Tag v0.4.0.
